require("src.globals")
require("src.commands")
require("src.bitbuf")

--- make them run before tickshift so we dont return before it
require("src.anticheat")
require("src.convars")

local spoof = require("src.spoof_convars")
local spectators = require("src.spectatorlist")
local aimbot = require("src.aimbot")
local esp = require("src.esp")
local tickshift = require("src.tickshift")
local antiaim = require("src.antiaim")
local visuals = require("src.visuals")
local movement = require("src.movement")
local chams = require("src.chams")
local binds = require("src.binds")

require("src.background")

callbacks.Unregister("CreateMove", "CM garlic bread spectator list")
callbacks.Register("CreateMove", "CM garlic bread spectator list", spectators.CreateMove)

callbacks.Unregister("CreateMove", "CM garlic bread cheat aimbot")
callbacks.Register("CreateMove", "CM garlic bread cheat aimbot", aimbot.CreateMove)
callbacks.Unregister("FrameStageNotify", "FSN garlic bread cheat aimbot frame stage")
callbacks.Register("FrameStageNotify", "FSN garlic bread cheat aimbot frame stage", aimbot.FrameStageNotify)
callbacks.Unregister("Draw", "DRAW garlic bread aimbot")
callbacks.Register("Draw", "DRAW garlic bread aimbot", aimbot.Draw)

callbacks.Unregister("CreateMove", "CM garlic bread esp")
callbacks.Unregister("Draw", "DRAW garlic bread esp")
callbacks.Register("CreateMove", "CM garlic bread esp", esp.CreateMove)
callbacks.Register("Draw", "DRAW garlic bread esp", esp.Draw)

callbacks.Unregister("Draw", "DRAW garlic bread spectator list")
callbacks.Register("Draw", "DRAW garlic bread spectator list", spectators.Draw)

--- this SendNetMsg overrides tickshift.SendNetMsg, gotta find a workaround or mix the two together (last option)
callbacks.Unregister("SendNetMsg", "NETMSG garlic bread spoof convars")
callbacks.Register("SendNetMsg", "NETMSG garlic bread spoof convars", spoof.SendNetMsg)

callbacks.Unregister("CreateMove", "CM garlic bread tick shifting")
callbacks.Register("CreateMove", "CM garlic bread tick shifting", tickshift.CreateMove)
callbacks.Unregister("SendNetMsg", "NETMSG garlic bread tick shifting")
callbacks.Register("SendNetMsg", "NETMSG garlic bread tick shifting", tickshift.SendNetMsg)
callbacks.Unregister("Draw", "DRAW garlic bread tick shifting")
callbacks.Register("Draw", "DRAW garlic bread tick shifting", tickshift.Draw)

callbacks.Unregister("CreateMove", "CM garlic bread anti aim")
callbacks.Register("CreateMove", "CM garlic bread anti aim", antiaim.CreateMove)
callbacks.Unregister("Draw", "DRAW garlic bread anti aim")
callbacks.Register("Draw", "DRAW garlic bread anti aim", antiaim.Draw)

callbacks.Unregister("RenderView", "RV garlic bread render view visuals")
callbacks.Register("RenderView", "RV garlic bread render view visuals", visuals.RenderView)
callbacks.Unregister("FrameStageNotify", "FSN garlic bread visuals frame stage")
callbacks.Register("FrameStageNotify", "FSN garlic bread visuals frame stage", visuals.FrameStageNotify)

callbacks.Unregister("CreateMove", "CM garlic bread movement")
callbacks.Register("CreateMove", "CM garlic bread movement", movement.CreateMove)

callbacks.Unregister("CreateMove", "CM garlic bread chams")
callbacks.Register("CreateMove", "CM garlic bread chams", chams.CreateMove)

callbacks.Unregister("DrawModel", "DME garlic bread chams")
callbacks.Register("DrawModel", "DME garlic bread chams", chams.DrawModel)

callbacks.Unregister("CreateMove", "CM garlic bread binds")
callbacks.Unregister("FireGameEvent", "GE garlic bread binds")
callbacks.Register("CreateMove", "CM garlic bread binds", binds.CreateMove)
callbacks.Register("FireGameEvent", "GE garlic bread binds", binds.FireGameEvent)

callbacks.Register("Unload", "UL garlic bread unload", function()
	callbacks.Unregister("CreateMove", "CM garlic bread spectator list")
	callbacks.Unregister("CreateMove", "CM garlic bread cheat aimbot")
	callbacks.Unregister("FrameStageNotify", "FSN garlic bread cheat aimbot frame stage")
	callbacks.Unregister("Draw", "DRAW garlic bread aimbot")
	callbacks.Unregister("Draw", "DRAW garlic bread spectator list")
	callbacks.Unregister("SendNetMsg", "NETMSG garlic bread spoof convars")
	callbacks.Unregister("CreateMove", "CM garlic bread tick shifting")
	callbacks.Unregister("SendNetMsg", "NETMSG garlic bread tick shifting")
	callbacks.Unregister("Draw", "DRAW garlic bread tick shifting")
	callbacks.Unregister("CreateMove", "CM garlic bread anti aim")
	callbacks.Unregister("Draw", "DRAW garlic bread anti aim")
	callbacks.Unregister("RenderView", "RV garlic bread render view visuals")
	callbacks.Unregister("FrameStageNotify", "FSN garlic bread visuals frame stage")
	callbacks.Unregister("CreateMove", "CM garlic bread movement")
	callbacks.Unregister("CreateMove", "CM garlic bread chams")
	callbacks.Unregister("DrawModel", "DME garlic bread chams")
	callbacks.Unregister("CreateMove", "CM garlic bread binds")
	callbacks.Unregister("FireGameEvent", "GE garlic bread binds")
	callbacks.Unregister("CreateMove", "CM garlic bread esp")
	callbacks.Unregister("Draw", "DRAW garlic bread esp")

	antiaim.unload()
	spoof.unload()
	spectators.unload()
	aimbot.unload()
	tickshift.unload()
	antiaim.unload()
	visuals.unload()
	movement.unload()
	chams.unload()
	binds.unload()
	esp.unload()
	GB_GLOBALS = nil
	collectgarbage("collect")
end)
